services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: energy
      POSTGRES_PASSWORD: energy
      POSTGRES_DB: energyops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3001:3000"
    depends_on:
      - postgres

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    depends_on:
      - postgres
    working_dir: /usr/app
    volumes:
      - ./dbt/energyops:/usr/app
      - ./dbt/profiles.docker.yml:/root/.dbt/profiles.yml:ro

volumes:
  pgdata:
